const assert = require('node:assert/strict');
const { setup, openLift, visitChocolate, reachCamera, floors } = require('./browser-helpers.cjs');
(async () => {
  const h = await setup(), { page } = h;
  try {
    await openLift(page, h.base);
    await page.locator('#floorMenu').click();
    assert.equal(await page.locator('#floorList .floor-option').count(), 45);
    assert.equal(await page.locator('#wallTabs button').count(), 6);
    for (const [wall, count] of [[1, 10], [2, 10], [3, 9], [4, 9], [5, 7]]) {
      await page.locator(`#wallTabs [data-wall="${wall}"]`).click();
      assert.equal(await page.locator('#floorList .floor-option').count(), count);
      assert.equal(await page.locator(`#wallTabs [data-wall="${wall}"]`).getAttribute('aria-pressed'), 'true');
    }
    await page.locator('#wallTabs [data-wall="0"]').click();
    await page.locator('#roomSearch').fill('Mossop');
    assert.equal(await page.locator('#floorList .floor-option').count(), 1);
    assert.equal(await page.locator('#floorList .floor-option').getAttribute('aria-label'), 'The Chocolate Room');
    await page.locator('#roomSearch').fill('there is no such room');
    assert.equal(await page.locator('#floorList .floor-option').count(), 0);
    assert.equal(await page.locator('#noRooms').isVisible(), true);
    await page.locator('#roomSearch').fill('');
    await page.screenshot({ path: 'artifacts/floors-mobile.png' });
    await page.locator('#closeFloors').click();
    await visitChocolate(page);
    await page.screenshot({ path: 'artifacts/chocolate-choice-mobile.png' });
    const ratio = await page.locator('#app').evaluate(e => e.clientWidth / e.clientHeight);
    assert.ok(Math.abs(ratio - 9 / 16) < 0.003);
    await reachCamera(page);
    assert.equal(await page.locator('#questText').innerText(), floors['chocolate-room'].needShort);
    assert.match(await page.locator('#questTitle').innerText(), /Mossop/);
    assert.ok((await page.evaluate(() => window.__spoken)).includes(floors['chocolate-room'].ask));
    assert.equal(await page.evaluate(() => journey.state), 'quest');
    assert.deepEqual(h.clips.map(p => p.beat), ['tour', 'instruction', 'ask']);
    assert.equal(h.clips[0].references.length, 1);
    assert.equal(h.clips[2].references.length, 2);
    const secondInstruction = await page.evaluate(async () => (await fetch(`/api/journey/${journey.id}/instruction`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ instruction: 'walk again' }) })).status);
    assert.equal(secondInstruction, 409);
    await page.waitForTimeout(600);
    await page.screenshot({ path: 'artifacts/camera-request-mobile.png' });
    const stream = await page.locator('#cameraView').evaluateHandle(v => v.srcObject);
    await page.locator('#takePhoto').click();
    assert.equal(await stream.evaluate(s => s.getTracks().every(t => t.readyState === 'ended')), true);
    const submittedPhoto = await page.locator('#shot').getAttribute('src');
    await page.locator('#submitPhoto').click();
    await page.locator('#reward').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#resultStamp').innerText(), 'A');
    assert.match(await page.locator('#resultCharacter').innerText(), /Mossop.*preview verdict/);
    assert.match(await page.locator('#rewardStatus').innerText(), /simulated/);
    assert.equal(await page.locator('#resultPhoto').getAttribute('src'), submittedPhoto);
    assert.equal(await page.locator('#retryResult').isVisible(), false);
    await page.screenshot({ path: 'artifacts/reward-mobile.png' });
    const denied = await page.evaluate(async () => (await fetch('/api/reward', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ journeyId: journey.id }) })).status);
    assert.equal(denied, 403);
    await page.reload(); await page.locator('#iris').click();
    await page.locator('#reward').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#resultPhoto').getAttribute('src'), submittedPhoto);
    assert.equal(await page.locator('#resultStamp').innerText(), 'A');
    await page.locator('#stepIn').click(); await page.waitForFunction(() => mode === 'idle');
    await visitChocolate(page); await reachCamera(page);
    await page.locator('#skipPhoto').click();
    await page.locator('#reward').waitFor({ state: 'visible' });
    assert.equal(await page.evaluate(() => journey.demoCompletion), true);
    assert.equal(await page.locator('#resultEvidence').isVisible(), false);
    await page.locator('#stepIn').click(); await page.waitForFunction(() => mode === 'idle');
    assert.deepEqual(h.errors, []);
    console.log('PASS: 45-room directory, five wall groups, character search, portrait tour, one instruction, complete request, camera cleanup, photo-backed preview stamp, reload and explicit skip.');
  } finally { await h.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
